import type { OpenApiSchema } from "../types.js";
import {
  array,
  CURRENCY,
  DATE_TIME,
  DECIMAL,
  JSON_VALUE,
  NONNEGATIVE_DECIMAL,
  nullable,
  object,
  UUID,
} from "../schema-helpers.js";

const reportRange = object(["from", "to", "timezone"], {
  from: DATE_TIME,
  to: DATE_TIME,
  timezone: { type: "string", minLength: 1, maxLength: 128 },
});

export const USAGE_COMPONENT_SCHEMAS: Readonly<Record<string, OpenApiSchema>> = {
  RequestDetails: object(["request_id", "attempts", "audit_history"], {
    request_id: { type: "string", minLength: 1, maxLength: 256 },
    attempts: array(
      object(
        [
          "request_id",
          "attempt_id",
          "attempt_index",
          "is_final_attempt",
          "operation_id",
          "user_id",
          "display_user",
          "virtual_model",
          "model_id",
          "connection_id",
          "connection_driver",
          "model_name",
          "request_model",
          "provider",
          "route_reason",
          "fallback_from",
          "event_time",
          "received_at",
          "status",
          "versions",
          "properties",
          "raw_event",
          "model_resolution",
          "usage",
          "model_cost",
          "aiu",
          "aiu_history",
          "projection",
          "failures",
        ],
        {
          request_id: { type: "string" },
          attempt_id: { type: "string" },
          attempt_index: { type: "integer", minimum: 0 },
          is_final_attempt: { type: "boolean" },
          operation_id: nullable({ type: "string" }),
          user_id: { type: "string", minLength: 1, maxLength: 256 },
          display_user: nullable({ type: "string", minLength: 1, maxLength: 256 }),
          virtual_model: nullable({ type: "string" }),
          model_id: nullable(UUID),
          connection_id: nullable(UUID),
          connection_driver: nullable({
            type: "string",
            enum: ["litellm", "openai_compatible", "anthropic"],
          }),
          model_name: nullable({ type: "string" }),
          request_model: nullable({ type: "string" }),
          provider: nullable({ type: "string" }),
          route_reason: nullable({ type: "string" }),
          fallback_from: nullable({ type: "string" }),
          event_time: DATE_TIME,
          received_at: DATE_TIME,
          status: { type: "string" },
          versions: object(["schema", "application", "sdk", "connector", "configuration"], {
            schema: { type: "string" },
            application: nullable({ type: "string" }),
            sdk: nullable({ type: "string" }),
            connector: nullable({ type: "string" }),
            configuration: nullable({ type: "string" }),
          }),
          properties: object(["event", "user"], {
            event: JSON_VALUE,
            user: JSON_VALUE,
          }),
          raw_event: object(
            ["event_id", "processing_status", "error", "payload_state", "payload"],
            {
              event_id: { type: "string" },
              processing_status: nullable({ type: "string" }),
              error: nullable({ type: "string" }),
              payload_state: { type: "string", enum: ["retained", "purged"] },
              payload: JSON_VALUE,
            },
          ),
          model_resolution: object(["status", "model_id", "request_model"], {
            status: { type: "string", enum: ["matched", "unmapped"] },
            model_id: nullable(UUID),
            request_model: nullable({ type: "string" }),
          }),
          usage: object(["input_tokens", "cached_input_tokens", "output_tokens", "total_tokens"], {
            input_tokens: NONNEGATIVE_DECIMAL,
            cached_input_tokens: NONNEGATIVE_DECIMAL,
            output_tokens: NONNEGATIVE_DECIMAL,
            total_tokens: NONNEGATIVE_DECIMAL,
          }),
          model_cost: nullable(
            object(["status", "total", "currency", "version_id", "lines"], {
              status: { type: "string" },
              total: nullable(NONNEGATIVE_DECIMAL),
              currency: nullable(CURRENCY),
              version_id: nullable(UUID),
              lines: array(JSON_VALUE),
            }),
          ),
          aiu: nullable(
            object(["status", "total_aiu_micros", "version_id", "lines"], {
              status: { type: "string" },
              total_aiu_micros: nullable(NONNEGATIVE_DECIMAL),
              version_id: nullable(UUID),
              lines: array(JSON_VALUE),
            }),
          ),
          aiu_history: array(
            object(
              [
                "id",
                "type",
                "used_change_aiu_micros",
                "reserved_change_aiu_micros",
                "used_after_aiu_micros",
                "reserved_after_aiu_micros",
                "reason",
                "created_at",
              ],
              {
                id: UUID,
                type: { type: "string" },
                used_change_aiu_micros: DECIMAL,
                reserved_change_aiu_micros: DECIMAL,
                used_after_aiu_micros: NONNEGATIVE_DECIMAL,
                reserved_after_aiu_micros: NONNEGATIVE_DECIMAL,
                reason: nullable({ type: "string" }),
                created_at: DATE_TIME,
              },
            ),
          ),
          projection: array(
            object(["event_type", "status", "attempt_count", "sent_at", "error"], {
              event_type: { type: "string" },
              status: nullable({ type: "string" }),
              attempt_count: { type: "integer", minimum: 0 },
              sent_at: nullable(DATE_TIME),
              error: nullable({ type: "string" }),
            }),
          ),
          failures: array(
            object(
              [
                "id",
                "stage",
                "code",
                "class",
                "status",
                "replay_count",
                "first_failed_at",
                "resolution",
              ],
              {
                id: UUID,
                stage: { type: "string" },
                code: { type: "string" },
                class: { type: "string" },
                status: { type: "string" },
                replay_count: { type: "integer", minimum: 0 },
                first_failed_at: DATE_TIME,
                resolution: nullable({ type: "string" }),
              },
            ),
          ),
        },
      ),
    ),
    audit_history: array(
      object(["action", "object_type", "object_id", "after", "reason", "created_at"], {
        action: { type: "string" },
        object_type: { type: "string" },
        object_id: { type: "string" },
        after: JSON_VALUE,
        reason: nullable({ type: "string" }),
        created_at: DATE_TIME,
      }),
    ),
  }),
  ReportEnvelope: object(["watermark", "lag_seconds", "range", "data"], {
    watermark: nullable(DATE_TIME),
    lag_seconds: nullable({ type: "integer", minimum: 0 }),
    range: nullable(reportRange),
    data: JSON_VALUE,
  }),
  BackgroundJob: object(
    [
      "id",
      "application_id",
      "type",
      "status",
      "idempotency_key",
      "parameters",
      "result",
      "attempts",
      "error",
      "created_at",
      "updated_at",
    ],
    {
      id: UUID,
      application_id: UUID,
      type: { type: "string" },
      status: { type: "string" },
      idempotency_key: { type: "string" },
      parameters: JSON_VALUE,
      result: JSON_VALUE,
      attempts: { type: "integer", minimum: 0 },
      error: nullable(
        object(["code", "message"], {
          code: { type: "string" },
          message: nullable({ type: "string" }),
        }),
      ),
      created_at: DATE_TIME,
      updated_at: DATE_TIME,
    },
  ),
};
